import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <head>
        <meta
          name="viewport"
          content="width=device-width, initial-scale=1.0"
        ></meta>
      </head>
      <body className={inter.className}>
        <div className="w-full h-full flex flex-col text-center">
          <div className="h-[220px]">Logo</div>
          <div>Hero Image</div>
          <div className="flex-grow">{children}</div>
          <div className="p-80 ">Footer</div>
        </div>
      </body>
    </html>
  );
}
